apiVersion: v1
kind: Service
metadata:
  name: blue-green-service
spec:
  type: NodePort
  selector:
    app: blue-green-app
    version: blue
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
